### ISSUE TITLE
getting a null on changelog type when using cursegradle 1.0.3

### ISSUE THREAD

**Issue by Vectron** [matthewprenger/CurseGradle#1]
when i try and use cursegradle version 1.0.3 i get the next error:

[link to Gradle Output](http://pastebin.com/iZe77SxS)

[link to build.gradle](https://github.com/Vectron/mapwriter/blob/1.8/build.gradle)

this error does not happen with version 1.0.1

**Comment by matthewprenger** [comment]
OK, as a temporary workaround until I get it fixed add `mainArtifact jar` inside the `project { }` block.

**Comment by Vectron** [comment]
that fixed it,

as a note i also had to add "addGameVersion" else the script wouldnt deploy to curseforge

**Comment by matthewprenger** [comment]
Yeah I need to update my ForgeGradle detection for FG2. It's on my TODO list.
