### ISSUE TITLE
use shadowJar / reobfShadowJar

### ISSUE THREAD

**Issue by NikkyAI** [matthewprenger/CurseGradle#13]
i am shading in libraries and relocating them with shadowJar

i tried

```
mainArtifact(shadowJar) {
    displayName = "MatterLink $version"
}
```

and `tasks.reobfShadowJar.mustRunAfter shadowJar`
but it seems that task does not reobsfucate the jar properly
and the reobfShadowJar task does not return a file

**Comment by TehNut** [comment]
What does this have to do with CurseGradle?

**Comment by NikkyAI** [comment]
i was asking for how to use it with cursegradle.. but it ended up gradle being just a bit weird.. i solved it

this did the trick for me
```
tasks.shadowJar.finalizedBy reobfShadowJar

curseforge {
    if (project.hasProperty('CURSEFORGE_API_TOKEN') && project.hasProperty('release')) {
        apiKey = CURSEFORGE_API_TOKEN
    }
    project {
        id = project.curse_id
        releaseType = project.curse_release_type
        mainArtifact(shadowJar) {
            displayName = "$rootProject.name-$version"
        }
    }
}
```
