### ISSUE TITLE
Curse API changed

### ISSUE THREAD

**Issue by UpcraftLP** [matthewprenger/CurseGradle#16]
uploading jars via CurseGradle does no longer work, because curse changed their API.

quoting Technostar:
`requiredLibrary and optionalLibrary are going to become requiredDependency and optionalDependency`

**Comment by jriwanek** [comment]
I'm working on a PR for it.

**Comment by UpcraftLP** [comment]
closed by #17

**Comment by matthewprenger** [comment]
https://plugins.gradle.org/plugin/com.matthewprenger.cursegradle

Version 1.1.0 has the fix.
