### ISSUE TITLE
requiredLibrary is being ignored

### ISSUE THREAD

**Issue by rubensworks** [matthewprenger/CurseGradle#2]
It looks like the required library relation is being ignored by this plugin.
The script does not seem to give any errors with the curseforge declaration found here: https://github.com/CyclopsMC/EvilCraft/blob/master-1.8/gradle/deploy.gradle#L13-L17
But any uploaded files do not show the required library on the curseforge file download page.

Am I missing something? Or is something going wrong with in plugin?
This used to work just fine with the integrated ForgeGradle system.

**Comment by matthewprenger** [comment]
@rubensworks Put `debug = true` inside the `curseforge { }` block and try again. It won't actually upload the file, but it will spit out the JSON to the console. See if the relations are being declared in there.

**Comment by matthewprenger** [comment]
b9be20b984d4ad8fed8e3a519af0aac125cc187e Should have fixed your issue. Update to 1.0.5
