### ISSUE TITLE
Java 9 detection is too eager

### ISSUE THREAD

**Issue by tterrag1098** [matthewprenger/CurseGradle#20]
Not sure what else to say. It marks my uploads as Java 9 compatible when I do not even have Java 9 on my system, nor is the source compatibility set that high. I believe the `compareTo` logic is backwards...

**Comment by matthewprenger** [comment]
The Java 9 logic is the exact same as the 6, 7, and 8 logic. https://github.com/matthewprenger/CurseGradle/blob/1.1.0/src/main/groovy/com/matthewprenger/cursegradle/Integration.groovy#L38-L49

It's not checking the upper boundary, but the lower one. For example if your compatibility is set to Java 7: Java 6 will **not** be added, but 7, 8, and 9 will.

**Comment by tterrag1098** [comment]
Right...but that's not how mods work. Forge isn't compatible with Java 9.

**Comment by matthewprenger** [comment]
Hmm, fair enough. I thought they fixed that. For the time being you can add the following afterEvaluate block to remove it:

```groovy
curseforge {
    project {
        id = '12345'

        afterEvaluate {
            gameVersionStrings.remove('Java 9')
        }
    }
}
```

**Comment by HenryLoenwind** [comment]
That workaround didn't work (for us)

https://github.com/SleepyTrousers/EnderIO/blob/master/build.gradle#L255

**Comment by UpcraftLP** [comment]
> Hmm, fair enough. I thought they fixed that. For the time being you can add the following afterEvaluate block to remove it:

do I have to make that `afterEvaluate`-block project-specific or can I just leave out the project ID?
