### ISSUE TITLE
Error in console (not failure) when doing any gradle task while cursegradle is enabled with ForgeGradle 3.+ for MC 1.13.2

### ISSUE THREAD

**Issue by The-Fireplace** [matthewprenger/CurseGradle#24]
After updating Forge to 1.13.2, and ForgeGradle with it, the following error began showing up in the console when running any gradle command. It disappears when I comment out cursegradle related code from my build.gradle. Note that this error does not appear to prevent cursegradle from working, it is just log spam.
https://paste.ubuntu.com/p/QkhyRNFsk6/

**Comment by henkelmax** [comment]
I have the same issue.
https://pastebin.com/ysCjZg4Z

**Comment by matthewprenger** [comment]
https://plugins.gradle.org/plugin/com.matthewprenger.cursegradle/1.2.0
