### ISSUE TITLE
Curseforge added support for modloaders per file

### ISSUE THREAD

**Issue by NikkyAI** [matthewprenger/CurseGradle#26]
I think thats all needed to say, hope it gets supported soon

**Comment by Darkhax** [comment]
This issue should be very easy to fix. Simply need to add support for it in his own validator. The relevant code can be found [here](https://github.com/matthewprenger/CurseGradle/blob/2f6ea93c4e241408fc49b18d6373e4758c41c031/src/main/groovy/com/matthewprenger/cursegradle/CurseVersions.groovy#L35-L39). 

The new modloader versions are in CurseForge's version response but they don't match the expected format by CurseGradle. Here are the relevant responses from the API for these versions. 

```json
{"id":7498,"gameVersionTypeID":68441,"name":"Forge","slug":"forge"},   

{"id":7499,"gameVersionTypeID":68441,"name":"Fabric","slug":"fabric"},   

{"id":7500,"gameVersionTypeID":68441,"name":"Rift","slug":"rift"}
```

**Comment by matthewprenger** [comment]
https://plugins.gradle.org/plugin/com.matthewprenger.cursegradle/1.4.0
