### ISSUE TITLE
CurseForge task fails with HTTP Error Code 503: Service Temporarily Unavailable

### ISSUE THREAD

**Issue by mrapplexz** [matthewprenger/CurseGradle#28]
Hello! The CurseForge task fails with HTTP 503 when I'm trying to run it. I think it happens because the website now uses CloudFlare :( .

**Used CurseGradle version**: 1.4.0
**Gradle output with stacktrace**: https://pastebin.com/HnDg82rw

**Comment by matthewprenger** [comment]
There isn't much I can do about 503 errors. I just tested the API endpoint from my connection and didn't see any issues.
