### ISSUE TITLE
Error: "Cannot add task ':curseforge' as a task with that name already exists."

### ISSUE THREAD

**Issue by DanielleHuisman** [matthewprenger/CurseGradle#3]
I'm using the ForgeGradle-2.1 snapshots and for some reason I get this error on my local machine and on CircleCI for one project: `Cannot add task ':curseforge' as a task with that name already exists.`
But another project on CircleCI with the exact same configuration does not get this error.

Full error: http://pastebin.com/2rXcH2Wc
Build scripts: 
- https://github.com/AgeCraft/AgeCraft/blob/1.8.8/build.gradle
- https://github.com/AgeCraft/ExtendedMetadata/blob/1.8.8/build.gradle

Examples on CircleCI: 
- Working: https://circleci.com/gh/AgeCraft/ExtendedMetadata/121
- Fail: https://circleci.com/gh/AgeCraft/AgeCraft/49

**Comment by AbrarSyed** [comment]
@matthewprenger I blame you

**Comment by DanielleHuisman** [comment]
Small note: it also happens on the latest version of CurseGradle (1.0.4)

**Comment by matthewprenger** [comment]
@DanielHuisman I just cloned your repo and tested in debug mode and I couldn't replicate the issue. My only thought is, are you using some kind of init script on the ci server that is creating a task called `curseforge`?

**Comment by DanielleHuisman** [comment]
No, the CI commands are in the circle.yml and all they do is use the Gradle wrapper to execute some commands.
I will try wiping my Gradle caches on my local machine and try it, but I already tried `clean` and refreshing dependencies.

**Comment by DanielleHuisman** [comment]
Ok, I removed my `.gradle` directory (both in my user folder and in the project folder) and removed the `build` folder, but I still get exactly the same error.

**Comment by matthewprenger** [comment]
Can you get me a log with `--info --stacktrace`?

**Comment by matthewprenger** [comment]
OK @DanielHuisman I figured it out. The problem is [this](https://github.com/AgeCraft/AgeCraft/blob/1.8.8/build.gradle#L166) line. You're creating a project with an empty string for the ID. CurseGradle creates a task for each project called `curseforge<ID>`, and the main task that uploads all projects called `curseforge`. Since there is no ID for that project, it's creating a duplicate task name. I would recommend changing that line to default to `noid` or something else.

**Comment by DanielleHuisman** [comment]
Face palm, forgot to set the env variables on CircleCI, but will apply your change to fix local builds.
