### ISSUE TITLE
How to get uploaded File ID

### ISSUE THREAD

**Issue by Redstoneguy129** [matthewprenger/CurseGradle#30]
How do i go about getting the file id of the uploaded artifact?

This is my build.gradle:
`curseforge {
    apiKey = key
    project {
        id = '386017'
        changelog = changeLog
        releaseType = modReleaseType
        relations {
            requiredDependency 'heroes-united'
        }
        addGameVersion mcVersion
        mainArtifact(jar) {
            displayName = title
        }
    }
}
`

**Comment by matthewprenger** [comment]
There isn't currently an officially exposed method to get at the file id. You'd need to do something like [this](https://github.com/TerraformersMC/Campanion/blob/36abac6b6a9ab2017468d615a762d06e985d2346/build.gradle#L235) to get it.
