### ISSUE TITLE
Building and uploading the wrong artifact

### ISSUE THREAD

**Issue by ljfa-ag** [matthewprenger/CurseGradle#4]
I got strange NoSuchMethodErrors with a Forge mod, and it turned out that CurseGradle 1.0.1 was building and uploading the deobfuscated jar (from the "jar" task), rather than the correct one that could be used as mod (from the "build" task).

**Comment by TehNut** [comment]
Why not use 1.0.4..?

**Comment by ljfa-ag** [comment]
Uhhh...I didn't notice there was a 1.0.4 ... I took the example code from the Wiki. Also I looked at the git tags and the newest one is 1.0.1. Why did you stop creating tags after that?

Sorry for the false alert, 1.0.4 seems to work. You should probably either update the wiki on new releases, or replace the "1.0.1" by a placeholder. And create tags ^^

**Comment by matthewprenger** [comment]
Oh whoops... forgot about git tags >_>
