### ISSUE TITLE
Feature Request: Specify Required Java Version

### ISSUE THREAD

**Issue by shadowfacts** [matthewprenger/CurseGradle#5]
CurseForge allows you to specify the required Java version for files, and it would be awesome if CurseGradle could pull this automatically from the project's `targetCompatibility`.

**Comment by matthewprenger** [comment]
I'm not sure that the [CurseForge API](https://github.com/curseforge/api) supports this. I'll poke curse people to confirm.

**Comment by matthewprenger** [comment]
@shadowfacts Apparently you can do this manually through `addGameVersion 'Java 8'`. I'll see about detecting and setting this automatically.
