### ISSUE TITLE
Invalid release type (alpha)

### ISSUE THREAD

**Issue by digitalseraphim** [matthewprenger/CurseGradle#6]
When setting the release type value using a config file, I get an error that looks like the following: 

> Invalid release type (alpha) for project <project id>. Valid options are: [alpha, beta, release]

in my config file I have:
`curse_release_type=alpha``

In my build.gradle I have:

```
curseforge  {
    apiKey = "${priv.curse_api_key}"
    project {
        id = "${config.curse_proj_id}"
        releaseType = "${config.curse_release_type}"
        mainArtifact jar
        addArtifact deobfJar
        addGameVersion "${config.minecraft_version}"
    }
}
```

If I change the "releaseType" line to 
`releaseType="alpha"`
it works just fine.

**Comment by The-Fireplace** [comment]
Have you tried
`curse_release_type="alpha"`
in your config file?
