### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by FireBall1725** [matthewprenger/CurseGradle#8]
Hey,
I don't know the extent of the API that you are using for CurseForge, but it would be awesome if it could be added to change the Project Description through CurseGradle, this way I could automate the readme from github getting updated to the Project Description.
Thanks,
Erin

**Comment by matthewprenger** [comment]
AFAIK this isn't possible according to Curse's API docs: https://www.curseforge.com/docs/api, and from what I've heard they don't have plans on expanding the API sadly.
